### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by PonchoPowers** [szikszail/cross-process-lock#39]
If another application comes along and writes to the file, it won't care about the lock file you've created, so while it is cross process, it is only effective for anything code using cross-process-lock.

To implement a proper solution, you would need to:

1. Check to see if the a file already exists or not, if it doesn't then create it.
2. Read and checksum the original data.
3. Check for any write handles on the file being written to, throw an error if any.
4. Write the data to the file.
5. Compare the checksum of the data with file being written to, and throw an error if there is a mismatch.

This is the only reliable way to ensure a write is successful.

**Comment by szikszail** [comment]
This is a known limitation and intended behavior, see https://cross-process-lock.6ai.lol/functions/lock.html: 

> Note, that it will be only a soft-lock, the file will be locked for other instances of cross-process-lock, or processes using the same API for locking.

I'll update the README to make this clear.

However, your contribution is welcome if you would like to propose a better solution.

Reviewing your proposed solution, it is unclear which part of the lifecycle it describes: lokc, unlock, or end-to-end. Also, I'm not sure how writing to the file with new (4th point) and then checking if the saved checksum is correct with the checksum of the written data (5th point) will pass ever, as the checksums will be different; they are made for different data.
